### ISSUE TITLE
PmagPy import syntax

### ISSUE THREAD

**Issue by lfairchild** [PmagPy/2016_Tauxe-et-al_PmagPy_Notebooks#3]
This is not really an issue, and is very easily fixed, but I wanted to point out (or be corrected about) a necessary change in syntax when importing PmagPy modules (pmag.py, ipmag.py, etc.) given the new directory structure. All of our Jupyter notebooks import these modules like so:

```
sys.path.insert(0, '/Users/Laurentia/PmagPy')
import pmag
import ipmag
import ipmagplotlib
```

This usually works fine for the remaining code -- however, I believe that this is actually importing code from the .pyc files that are in the main repo, which do not automatically update when changes are made to the .py files within the pmagpy folder. (I figured this out after a little confusion about why changes to ipmag.py were not implementing in the rest of the notebook.) To make sure to import the actual .py files, I think our syntax needs to be slightly modified to

```
sys.path.insert(0, '/Users/Laurentia/PmagPy')
from pmagpy import pmag, ipmag, ipmagplotlib
```

so that it pulls these modules from the PmagPy folder. Just wanted to point out this change for current and future notebooks!

**Comment by Swanson-Hysell** [comment]
I think that a preferable why to do the imports with the reorganization is to have the following in one's .bash_profile

```
export PYTHONPATH=$PYTHONPATH:~/PmagPy/
```

and then to do the imports line by line like this:

```
import pmagpy.ipmag as ipmag
import pmagpy.pmagplotlib as pmagplotlib
import pmagpy.pmag as pmag
```

That way there is no need to deal with importing sys and setting the path within each notebook.

**Comment by Swanson-Hysell** [comment]
Why don't you give this syntax a try and once you have implemented it in the notebooks we can close this issue?

**Comment by lfairchild** [comment]
Seems to be working properly - I've changed the import statements in both notebooks.
